# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org3
    Domain: org3.example.com
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1
