version: '3.3'
networks:
    myNetwork:
        external:
            name: myNetwork
services:
    peer2_org1:
        deploy:
            replicas: 1
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == pt-corcto17937
        image: hyperledger/fabric-peer:latest
        hostname: peer2.org1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=myNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=myNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_ID=peer2.org1.example.com
            - CORE_PEER_ADDRESS=peer2.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
            - 11051:7051
            - 11053:7053
        networks:
            myNetwork: 
                aliases: 
                    - peer2.org1.example.com
